apiVersion: v1
kind: Service
metadata:
  name: vprodb        #this name should be same as in application prop file
spec:
  selector:
    app: vprodb       #this name is our db name.. given in vprodb file(metadata labels)
  ports:
  - port: 3306
    targetPort: vprodb-port   #this name is also given in vprodb file
    protocol: TCP
  type: ClusterIP

