apiVersion: v1
kind: Service
metadata:
  name: vprocache01   #This name comes from app pro =p file
spec:
  selector:
    app: vpromc       #this is memcached name 
  ports:
  - port: 11211
    targetPort: vpromc-port     #this name is also given in vpromc file
    protocol: TCP
  type: ClusterIP