apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  selector:
    matchLabels:
      app: vprodb
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      containers:
      - name: vprodb
        image: gokulb12/vprodb:v1
        args:
          - "ignore-db-dir=lost+found"
        ports:
        - containerPort: 3306
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: vprodb-data
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: db-pass
      nodeSelector:
        zone: us-east-1a
      volumes:
        - name: vprodb-data
          awsElasticBlockStore:
            volumeID: vol-0c522f606851da85d
            fsType: ext4

  
                

      
